api:
  dashboard: false
  insecure: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: ${TRAEFIK_NETWORK_NAME}
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: ${TRAEFIK_ENTRYPOINT}
          scheme: https
  ${TRAEFIK_ENTRYPOINT}:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: {{ email }}
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
